# Generated by Django 4.1.7 on 2023-02-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_custom_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='custom',
            new_name='customer',
        ),
    ]
